version: '3.8'
services:
  ms-catalogo:
    image: ms-catalogo:v1.0
    environment:
      - FLASK_CONTEXT=${FLASK_CONTEXT}
      - FLASK_APP=${FLASK_APP}
      - SECRET_KEY=${SECRET_KEY}
      - SQLALCHEMY_TRACK_MODIFICATIONS=${SQLALCHEMY_TRACK_MODIFICATIONS}  
      - SQLALCHEMY_RECORD_QUERIES=${SQLALCHEMY_RECORD_QUERIES}
      - PROD_DB_URI=${PROD_DB_URI}
    ports:
      - "3001:3001"
    networks:
      - ecommerce_red
    
networks:
  ecommerce_red:
    external: true  
